Lpmem hashtable
efeslab/strata pull request #1
Opened 2019-08-26 17:16 UTC by eshiple

implemented hash table block allocator + lblk->pblk translation with simd, fixed json output for filebench, cuckoo hashtable block allocator,

2019-08-26 17:27 UTC, iangneal commented
Too many files added! Remove the benchout stuff at least.

2019-08-26 19:20 UTC, iangneal requested changes
Left you some general comments as well.

2019-08-26 19:20 UTC, iangneal commented on bench/BenchmarkProcesses.py
> +        mkfs_args = [ 'sudo', '-E', str(self.kernfs_path / 'mkfs.sh') ]
Do we need this?

2019-08-26 19:20 UTC, iangneal commented on kernfs/extents.c
> +	//printf("hello world\n");
I don't think we need this :)

2019-08-26 19:20 UTC, iangneal commented on kernfs/extents.c
> +	int create2 = flags & MLFS_GET_BLOCKS_CREATE_META;
create2 isn't a great variable name

2019-08-26 19:20 UTC, iangneal commented on kernfs/extents.c
> +	printf("HELLO WORLD\n");
plz remove

2019-08-26 19:20 UTC, iangneal commented on kernfs/fs.c
> +	printf("%s\n", js_str);
Extra

2019-08-26 19:20 UTC, iangneal commented on kernfs/lpmem_ghash.c
> +#ifdef SEQ_STEP
In general maybe just remove things that aren't being used to make this easier to read

2019-08-26 19:20 UTC, iangneal commented on kernfs/migrate.c
> +		// mlfs_assert(map.m_pblk != 0);
Can we add back this assert for each case?

2019-08-26 19:20 UTC, iangneal commented on kernfs/tests/Makefile
> +DEBUG = -g -O3 -march=skylake-avx512 -mavx -mavx512f -mavx512vl -mavx512cd -mavx512bw -mavx512dq
DEBUG should have -O0 since it's easier to step through

2019-08-26 19:20 UTC, iangneal commented on libfs/src/filesystem/dirent.c
> +		else {
I personally prefer the `} else {` style

2019-08-26 19:20 UTC, iangneal commented on libfs/src/filesystem/dirent.c
> +
Remove extra lines

2019-08-26 19:20 UTC, iangneal commented on libfs/src/mkfs/mkfs.c
> +					addr_t index;
Are all the comments needed?

2019-08-26 19:20 UTC, iangneal commented on libfs/src/mkfs/mkfs.c
> +						pmem_cuckoohash_create(inum, 0, &index);
Also are these tabs or spaces?

2019-08-26 19:20 UTC, iangneal commented on libfs/src/storage/storage.h
> +static uint64_t dev_size[g_n_devices + 1] = {0UL, 10567548928UL, 0UL, 0UL, 2111832064UL};
Don't stage these changes generally

2019-08-26 19:20 UTC, iangneal commented on libfs/src/storage/storage.c
> +	(char *)"/dev/dax0.2",
Don't stage these changes generally.

2019-08-26 19:20 UTC, iangneal commented on libfs/tests/write_bench.c
> +#include <stdio.h>
Can you add an explanation at the top about why this exists and how you use it?

2019-08-26 19:20 UTC, iangneal commented on libfs/tests/read_bench.c
> +#include <stdio.h>
Can you add an explanation at the top about why this test exists and how you use it?

2019-08-26 19:20 UTC, iangneal commented on utils/use_dax.sh
> +	sudo ndctl create-namespace -m dax -e namespace0.1 -f
Don't think we need this either

2019-08-27 16:44 UTC, eshiple commented on bench/BenchmarkProcesses.py
> +        mkfs_args = [ 'sudo', '-E', str(self.kernfs_path / 'mkfs.sh') ]
I think this was our solution to adding propogating env through bash scripts calling other bash scripts

2019-08-27 16:50 UTC, eshiple commented on kernfs/migrate.c
> +		// mlfs_assert(map.m_pblk != 0);
i think so

2019-08-27 16:53 UTC, eshiple commented on kernfs/tests/mkfs.sh
> +#! /bin/bash
here is where we removed sudo and added it to the python script

2019-08-27 16:55 UTC, eshiple commented on libfs/src/mkfs/mkfs.c
> +						pmem_cuckoohash_create(inum, 0, &index);
tabs?

2019-08-27 17:32 UTC, iangneal commented on bench/BenchmarkProcesses.py
> +        mkfs_args = [ 'sudo', '-E', str(self.kernfs_path / 'mkfs.sh') ]
I don't think we need the sudo though if you `sudo chown user:user /dev/daxWhatever`

2019-08-27 17:49 UTC, iangneal commented on kernfs/hash_functions.h
> +../../nvm-file-indexing/api/common/hash_functions.h
Might want to copy this rather thank sim-linking.

2019-08-27 17:49 UTC, iangneal commented on kernfs/lookup3.c
> +/*
Do we need this file?

2019-08-27 17:49 UTC, iangneal commented on kernfs/lpmem_cuckoo_hash_impl.c
> +/*
Do we need this file?

2019-08-27 17:49 UTC, iangneal commented on kernfs/lpmem_cuckoo_hash_impl.h
> +/*
Do we need this file?

2019-08-27 17:49 UTC, iangneal commented on kernfs/lpmem_cuckoohash.c
> +#include <stdbool.h>
Do we need this file?

2019-08-27 17:49 UTC, iangneal commented on kernfs/lpmem_cuckoohash.h
> +#ifndef __NVM_IDX_CUCKOO_HASH__
Do we need this file?

2019-08-27 17:49 UTC, iangneal commented on kernfs/lpmem_ghash.c
> + */
This comment can definitely be removed.

2019-08-27 17:49 UTC, iangneal commented on kernfs/lpmem_ghash.c
> +#endif
Is SIMPLE_ENTRIES used anywhere?

2019-08-27 17:49 UTC, iangneal commented on kernfs/lpmem_ghash.h
> +#define SIMPLE_ENTRIES
Is this used fore anything anymore? Can we consolidate?

2019-08-27 17:49 UTC, iangneal commented on kernfs/tests/mkfs.sh
> +#! /bin/bash
Ideally I'd like to remove all sudos since it's easier to automate.

2019-08-27 17:49 UTC, iangneal commented on libfs/src/filesystem/fs.c
> +            ret = bmap_hashfs(ip, &bmap_req_arr);
4 space indent

2019-08-27 17:49 UTC, iangneal commented on libfs/src/filesystem/fs.c
> +            bh = bh_get_sync_IO(bmap_req.dev, bmap_req_arr.block_no[0], BH_NO_DATA_ALLOC);
4 space indent

2019-08-27 17:49 UTC, iangneal commented on libfs/src/filesystem/hash_functions.h
> +../../../../nvm-file-indexing/api/common/hash_functions.h
Still might want to copy this directly

2019-08-27 17:49 UTC, iangneal commented on libfs/tests/MTCCcorrect.c
> +#include <stdio.h>
Comment at the top

2019-08-27 17:49 UTC, iangneal commented on libfs/tests/Makefile
> +write_bench: write_bench.c
Remove the rules if the files are gone.

2019-08-27 17:49 UTC, iangneal commented on shim/glibc-2.19/intl/plural.c
> -/* A Bison parser, made by GNU Bison 2.7.  */
Remove this file if you can

2019-08-27 17:49 UTC, iangneal requested changes
Round 2

2019-08-27 20:18 UTC, iangneal commented
I think all the comments remaining are just nitpicks, so just fix them when you can.

2019-09-03 16:30 UTC, eshiple commented on bench/BenchmarkProcesses.py
> +        mkfs_args = [ 'sudo', '-E', str(self.kernfs_path / 'mkfs.sh') ]
you might be right... but we use sudo for the mlfs.mkfs script normally. Or at least I have been.

2019-09-03 16:42 UTC, eshiple commented on kernfs/lpmem_cuckoohash.h
> +#ifndef __NVM_IDX_CUCKOO_HASH__
no

2019-09-03 16:42 UTC, eshiple commented on kernfs/lpmem_cuckoohash.c
> +#include <stdbool.h>
no

2019-09-03 16:42 UTC, eshiple commented on kernfs/lpmem_cuckoo_hash_impl.h
> +/*
no

2019-09-03 16:42 UTC, eshiple commented on kernfs/lpmem_cuckoo_hash_impl.c
> +/*
no

2019-09-06 17:30 UTC, iangneal approved these changes

2019-09-06 17:30 UTC, merged